<project name="micro-x-engine" default="jar">
  <property file="build.properties"/>
  <property name="build" value="build"/>
  <target name="clean"><delete dir="${build}"/><delete file="micro-x-engine.jar"/><delete file="micro-x-engine.jad"/></target>
  <target name="compile">
    <mkdir dir="${build}/classes"/>
    <javac srcdir="src" destdir="${build}/classes" source="1.3" target="1.3" bootclasspath="${cldc.jar}:${midp.jar}:${m3g.jar}" includeantruntime="false" debug="${debug}"/>
  </target>
  <target name="preverify" depends="compile">
    <mkdir dir="${build}/verified"/>
    <exec executable="${wtk.home}/bin/preverify" failonerror="true"><arg value="-classpath"/><arg value="${cldc.jar}:${midp.jar}:${m3g.jar}"/><arg value="-d"/><arg value="${build}/verified"/><arg value="${build}/classes"/></exec>
  </target>
  <target name="jar" depends="preverify">
    <copy todir="${build}/verified"><fileset dir="res"/></copy>
    <jar destfile="micro-x-engine.jar" manifest="MANIFEST.MF" basedir="${build}/verified"/>
    <length file="micro-x-engine.jar" property="jar.size"/>
    <copy file="MANIFEST.MF" tofile="micro-x-engine.jad"/>
    <echo file="micro-x-engine.jad" append="true">MIDlet-Jar-URL: micro-x-engine.jar${line.separator}MIDlet-Jar-Size: ${jar.size}${line.separator}</echo>
  </target>
</project>
