# MTJ Build Properties
KEmulator.includes=src/.classpath\
,src/.project\
,src/App.java\
,src/Canvas.java\
,src/CodeStrings.java\
,src/Combat.java\
,src/CombatEntity.java\
,src/Entity.java\
,src/EntityDef.java\
,src/EntityMonster.java\
,src/EntityStrings.java\
,src/Enums.java\
,src/FileStrings.java\
,src/Font.rff\
,src/Game.java\
,src/GameSprite.java\
,src/Graphics.java\
,src/HackingGame.java\
,src/Hud.java\
,src/IStringConstants.java\
,src/Images.java\
,src/Languages.java\
,src/LerpSprite.java\
,src/META-INF/MANIFEST.MF\
,src/MapEnums.java\
,src/MatrixSkip_button.png\
,src/MayaCamera.java\
,src/MenuItem.java\
,src/MenuStrings.java\
,src/MenuSystem.java\
,src/Menus.java\
,src/ParticleSystem.java\
,src/PlatformVars.java\
,src/Player.java\
,src/PowerUp_arrow_down.png\
,src/PowerUp_arrow_up.png\
,src/PowerUp_submit.png\
,src/Render.java\
,src/Resource.java\
,src/ScriptThread.java\
,src/SentryBotGame.java\
,src/Sound.java\
,src/Sounds.java\
,src/Span.java\
,src/SpanTexture.java\
,src/SpanTransparent.java\
,src/Strings.java\
,src/TGLEdge.java\
,src/TGLVert.java\
,src/Text.java\
,src/TinyGL.java\
,src/Translations.java\
,src/VendingMachine.java\
,src/boot.png\
,src/charmap\
,src/dpad.png\
,src/dpad_d.png\
,src/dpad_l.png\
,src/dpad_r.png\
,src/dpad_u.png\
,src/entities.bin\
,src/hdr\
,src/icon.png\
,src/images.idx\
,src/images0.bin\
,src/images1.bin\
,src/images2.bin\
,src/images3.bin\
,src/inGame_menu_elements.png\
,src/l1.png\
,src/l2.png\
,src/logo.png\
,src/m_01.java\
,src/m_02.java\
,src/m_03.java\
,src/m_04.java\
,src/m_05.java\
,src/m_06.java\
,src/m_07.java\
,src/m_08.java\
,src/m_09.java\
,src/m_test.java\
,src/main_menu_elements.png\
,src/main_menu_quadrant.png\
,src/map00.bin\
,src/map01.bin\
,src/map02.bin\
,src/map03.bin\
,src/map04.bin\
,src/map05.bin\
,src/map06.bin\
,src/map07.bin\
,src/map08.bin\
,src/map09.bin\
,src/menus.bin\
,src/moregames\
,src/newMappings.bin\
,src/newPalettes.bin\
,src/sniper_elements.png\
,src/softkey_button.png\
,src/softkey_switch.png\
,src/sounds.idx\
,src/sounds0.bin\
,src/sounds1.bin\
,src/sounds10.bin\
,src/sounds11.bin\
,src/sounds12.bin\
,src/sounds13.bin\
,src/sounds14.bin\
,src/sounds15.bin\
,src/sounds16.bin\
,src/sounds17.bin\
,src/sounds18.bin\
,src/sounds19.bin\
,src/sounds2.bin\
,src/sounds20.bin\
,src/sounds21.bin\
,src/sounds22.bin\
,src/sounds23.bin\
,src/sounds24.bin\
,src/sounds25.bin\
,src/sounds3.bin\
,src/sounds4.bin\
,src/sounds5.bin\
,src/sounds6.bin\
,src/sounds7.bin\
,src/sounds8.bin\
,src/sounds9.bin\
,src/strings.idx\
,src/strings0.bin\
,src/strings1.bin\
,src/strings10.bin\
,src/strings11.bin\
,src/strings12.bin\
,src/strings2.bin\
,src/strings3.bin\
,src/strings4.bin\
,src/strings5.bin\
,src/strings6.bin\
,src/strings7.bin\
,src/strings8.bin\
,src/strings9.bin\
,src/t_de\
,src/t_en\
,src/t_es-es\
,src/t_fr-fr\
,src/t_it\
,src/tables.bin\
,src/tex00.bin\
,src/tex01.bin\
,src/tex02.bin\
,src/tex03.bin\
,src/tex04.bin\
,src/tex05.bin\
,src/tex06.bin\
,src/tex07.bin\
,src/tex08.bin\
,src/tex09.bin\
,src/tex10.bin\
,src/tex11.bin\
,src/tex12.bin\
,src/tex13.bin\
,src/com/ea/sdk/SDKMoreGames.java\
,src/com/ea/sdk/SDKMoreGamesCheats.java\
,src/com/ea/sdk/SDKString.java\
,src/com/ea/sdk/SDKTextUtils.java\

KEmulator.excludes=\

