package com.microx.engine.world;
import com.microx.engine.math.Fixed;import com.microx.tools.AssetConverter;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;

/** Dependency-free desktop regression tests for converter and runtime world modules. */
public final class WorldFormatTest {
 public static void main(String[] args)throws Exception{Path dir=Files.createTempDirectory("mxl2-test");Path source=dir.resolve("level.level"),binary=dir.resolve("level.lvl");Files.write(source,level().getBytes(StandardCharsets.UTF_8));AssetConverter.writeLevel(source,binary);byte[] valid=Files.readAllBytes(binary);LevelLoader loader=new LevelLoader();ok(loader.load(new ByteArrayInputStream(valid)),"valid binary");ok(loader.world.portalReverse(0)==1,"reverse portal");ok(loader.findTransition(100)==0,"transition id");wallSlideAndStep(loader.collision);ok(loader.world.crossedPortal(Fixed.fromInt(4),Fixed.fromInt(1),0,Fixed.fromInt(5),Fixed.fromInt(1),0)==0,"room crossing");byte[] truncated=new byte[valid.length-1];System.arraycopy(valid,0,truncated,0,truncated.length);PortalWorld published=loader.world;ok(!loader.load(new ByteArrayInputStream(truncated)),"truncated rejected");ok(loader.world==published,"failed load is atomic");byte[] version=(byte[])valid.clone();version[5]=2;ok(!new LevelLoader().load(new ByteArrayInputStream(version)),"version rejected");Files.write(source,level().replace("portal 11 1 0 4 6 1 3 -1 1 0 -1","portal 11 9 0 4 6 1 3 -1 1 0 -1").getBytes(StandardCharsets.UTF_8));boolean rejected=false;try{AssetConverter.writeLevel(source,binary);}catch(IOException expected){rejected=true;}ok(rejected,"bad room reference rejected");System.out.println("WorldFormatTest: OK");}
 private static void wallSlideAndStep(Collision c){int one=Fixed.ONE;c.sweep(0,0,0,Fixed.fromInt(6),Fixed.fromInt(2),one/4,Fixed.fromInt(2),one/2);ok(c.resultX<Fixed.fromInt(5),"wall blocks sweep");ok(c.resultZ>0,"wall slide retains tangent motion");c.sweep(Fixed.fromInt(3),0,0,Fixed.fromInt(2),0,one/4,Fixed.fromInt(2),one/2);ok(c.resultX<Fixed.fromInt(4),"high step rejected");ok(c.ceilingHeight(0,0)==Fixed.fromInt(4),"ceiling query");ok(!c.hasClearance(0,Fixed.fromInt(3),0,Fixed.fromInt(2)),"low ceiling clearance");}
 private static void ok(boolean value,String message){if(!value)throw new AssertionError(message);}
 private static String level(){return "MXL2\ncounts 2 3 2 7 2 2 1 1 8\nroom -5 5 -5 5\nroom 5 15 -5 5\nfloor 0 -5 4 -5 5 0\nfloor 0 4 5 -5 5 1\nfloor 1 5 15 -5 5 1\nceiling 0 -5 5 -5 5 4\nceiling 1 5 15 -5 5 4\nedge 0 -5 -5 5 -5 0 4\nedge 0 -5 5 5 5 0 4\nedge 0 -5 -5 -5 5 0 4\nedge 0 5 -5 5 -1 0 4\nedge 0 5 1 5 5 0 4\nedge 1 5 -5 15 -5 0 4\nedge 1 5 5 15 5 0 4\nportal 10 0 1 4 6 1 3 -1 1 1 0\nportal 11 1 0 4 6 1 3 -1 1 0 -1\nspawn 0 0 0 0 0 0\nspawn 1 1 7 1 0 180\ntransition 100 1 test\nentity 1 10 1 0 100\n";}
}
