package com.microx.engine.gameplay;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;

/** Compact immutable-at-runtime gameplay descriptions generated by AssetConverter. */
public final class GameplayTables {
    public static final int MAGIC = 0x4d584732, MAX_TABLES = 16, MAX_ROWS = 256;
    private String[] table, key, text, meta;
    private short[] id, first, count;
    public boolean load(String resource) {
        InputStream in = getClass().getResourceAsStream(resource);
        return in != null && load(in);
    }
    public boolean load(InputStream stream) {
        try {
            DataInputStream in = new DataInputStream(stream);
            if (in.readInt() != MAGIC) return false;
            int tables = in.readUnsignedByte();
            if (tables > MAX_TABLES) return false;
            table = new String[tables]; first = new short[tables]; count = new short[tables];
            id = new short[1024]; key = new String[1024]; text = new String[1024];
            meta = new String[1024];
            int total = 0;
            for (int i = 0; i < tables; i++) {
                table[i] = in.readUTF(); first[i] = (short) total;
                int n = in.readUnsignedShort();
                if (n > MAX_ROWS || total + n > 1024) return false;
                count[i] = (short) n;
                for (int j = 0; j < n; j++) {
                    id[total] = (short) in.readUnsignedShort();
                    key[total] = in.readUTF(); text[total] = in.readUTF(); meta[total] = in.readUTF();
                    total++;
                }
            }
            return in.read() == -1;
        } catch (IOException invalid) { return false; }
        finally { try { stream.close(); } catch (IOException ignored) {} }
    }
    public int find(String tableName, int stableId) {
        for (int t = 0; t < table.length; t++)
            if (table[t].equals(tableName))
                for (int i = first[t] & 65535, end = i + (count[t] & 65535); i < end; i++)
                    if ((id[i] & 65535) == stableId) return i;
        return -1;
    }
    public String key(int row) { return key[row]; }
    public String text(int row) { return text[row]; }
    public String meta(int row) { return meta[row]; }
    public boolean containsCoreIds() {
        return find("npcs", GameIds.NPC_SIDOROVICH) >= 0
                && find("dialogs", GameIds.DIALOG_INTRO) >= 0
                && find("quests", GameIds.QUEST_FIND_STASH) >= 0;
    }
}
