package com.microx.engine.render;
import com.microx.engine.assets.TextureData;import com.microx.engine.math.Fixed;import com.microx.engine.world.PortalWorld;import com.microx.tools.AssetConverter;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;
public final class RenderingTest {
 public static void main(String[] a)throws Exception{objImport();clippingAndWinding();depthAndUv();portalOcclusion();budget();System.out.println("RenderingTest: OK");}
 private static void objImport()throws Exception{Path d=Files.createTempDirectory("mx-obj"),o=d.resolve("r.obj"),m=d.resolve("r.mesh");Files.write(o,("# microx material wall 3\no room_2\nv 0 0 2\nv 1 0 2\nv 1 1 2\nv 0 1 2\nvt 0 0\nvt 1 0\nvt 1 1\nvt 0 1\nusemtl wall\nf -4/-4 -3/-3 -2/-2 -1/-1\n").getBytes(StandardCharsets.US_ASCII));AssetConverter.writeModel(o,m);DataInputStream in=new DataInputStream(Files.newInputStream(m));ok(in.readInt()==0x4d584d32&&in.readUnsignedShort()==2,"MXM2 v2");ok(in.readUnsignedShort()==1,"section");ok(in.readUnsignedShort()==2&&in.readShort()==3,"metadata");ok(in.readUnsignedShort()==4&&in.readUnsignedShort()==2,"triangulation/dedup");in.close();}
 private static void clippingAndWinding(){Clipper c=new Clipper();ok(c.clip(-Fixed.ONE,0,Fixed.ONE/16,0,0,Fixed.ONE,0,Fixed.ONE,Fixed.ONE,0,0,Fixed.ONE,Fixed.ONE,0,Fixed.ONE,Fixed.ONE/8)>=3,"clipping");int[] rgb=new int[64];short[] z=new short[64];Rasterizer r=new Rasterizer();r.target(rgb,z,8,8);r.clear(0);TextureData t=texture(0xffffff);ok(!r.draw(1,1,Fixed.ONE,0,0,6,1,Fixed.ONE,0,0,1,6,Fixed.ONE,0,0,t),"winding culled");ok(r.draw(1,1,Fixed.ONE,0,0,1,6,Fixed.ONE,0,0,6,1,Fixed.ONE,0,0,t),"winding drawn");}
 private static void depthAndUv(){int[] rgb=new int[64];short[] z=new short[64];Rasterizer r=new Rasterizer();r.target(rgb,z,8,8);r.clear(0);r.draw(1,1,Fixed.fromInt(4),0,0,1,6,Fixed.fromInt(4),0,0,6,1,Fixed.fromInt(4),0,0,texture(0xff0000));r.draw(1,1,Fixed.ONE,0,0,1,6,Fixed.ONE,0,0,6,1,Fixed.ONE,0,0,texture(0x00ff00));ok(rgb[18]==0x00ff00,"depth ordering");TextureData t=new TextureData(2,1,new int[]{0x112233,0xabcdef},new byte[]{0,1});ok(t.sample(0,0)==0x112233&&t.sample(Fixed.ONE,0)==0xabcdef,"UV sampling");}
 private static void portalOcclusion(){PortalWorld w=new PortalWorld(3,2);w.room(0,-Fixed.ONE,Fixed.ONE,-Fixed.ONE,Fixed.ONE);w.room(1,-Fixed.ONE,Fixed.ONE,Fixed.ONE,Fixed.fromInt(3));w.room(2,-Fixed.ONE,Fixed.ONE,Fixed.fromInt(3),Fixed.fromInt(5));w.portal(0,0,0,1,-Fixed.ONE/4,Fixed.ONE/4,0,Fixed.ONE,Fixed.ONE,Fixed.ONE,-1,-1);w.portal(1,1,1,2,Fixed.fromInt(10),Fixed.fromInt(11),0,Fixed.ONE,Fixed.fromInt(2),Fixed.fromInt(2),-1,-1);ok(w.updateVisibility(0,0,0,0,Fixed.ONE,Fixed.fromInt(40),Fixed.fromInt(40),80,80)==2,"portal occlusion");ok(w.visibleRight(1)-w.visibleLeft(1)<80,"portal clip rect");}
 private static void budget(){TextureData t=new TextureData(256,256,new int[256],new byte[65536]);ok(t.memoryBytes()==66576,"atlas footprint");ok(240L*320L*6L<2L*1024L*1024L*45L/100L,"buffer budget");}
 private static TextureData texture(int c){return new TextureData(1,1,new int[]{c},new byte[]{0});}private static void ok(boolean v,String m){if(!v)throw new AssertionError(m);}
}
