package com.microx.engine.save;
import java.io.*;

/** Two-phase append protocol: PREP contains data; COMMIT makes it visible. Older commits remain fallback. */
public final class SaveStore {
 private static final int PREP=0x50524550,COMMIT=0x434f4d54;private final RecordBackend records;private final SaveCodec codec=new SaveCodec();
 public SaveStore(RecordBackend backend){records=backend;}
 public synchronized void save(SaveData data)throws SaveException{try{byte[] payload=codec.encode(data);ByteArrayOutputStream raw=new ByteArrayOutputStream();DataOutputStream out=new DataOutputStream(raw);out.writeInt(PREP);out.writeByte(data.slot);out.writeInt(data.sequence);out.writeInt(payload.length);out.write(payload);out.writeInt(SaveCodec.checksum(payload,0,payload.length));out.flush();int prepared=records.add(raw.toByteArray());codec.decode(payload);raw.reset();out=new DataOutputStream(raw);out.writeInt(COMMIT);out.writeByte(data.slot);out.writeInt(data.sequence);out.writeInt(prepared);out.writeInt(SaveCodec.checksum(payload,0,payload.length));out.flush();records.add(raw.toByteArray());}catch(SaveException e){throw e;}catch(Exception e){throw new SaveException("RecordStore write failed; previous commit remains valid",e);}}
 public synchronized SaveData load(int slot)throws SaveException{try{int[] ids=records.ids();SaveException rejected=null;int bestSequence=-1;SaveData best=null;for(int i=ids.length-1;i>=0;i--){byte[] commit=records.get(ids[i]);if(commit==null||commit.length!=17||readInt(commit,0)!=COMMIT||(commit[4]&255)!=slot)continue;int sequence=readInt(commit,5),prepared=readInt(commit,9),expected=readInt(commit,13);if(sequence<=bestSequence)continue;try{byte[] record=records.get(prepared);if(readInt(record,0)!=PREP||record.length<21||(record[4]&255)!=slot||readInt(record,5)!=sequence)throw new SaveException("commit metadata mismatch");int length=readInt(record,9);if(length<1||13+length+4!=record.length)throw new SaveException("invalid prepared length");byte[] payload=new byte[length];System.arraycopy(record,13,payload,0,length);int checksum=SaveCodec.checksum(payload,0,length);if(checksum!=expected||checksum!=readInt(record,13+length))throw new SaveException("transaction checksum mismatch");SaveData candidate=codec.decode(payload);if(candidate.slot!=slot||candidate.sequence!=sequence)throw new SaveException("slot metadata mismatch");best=candidate;bestSequence=sequence;}catch(Exception invalid){rejected=invalid instanceof SaveException?(SaveException)invalid:new SaveException("invalid committed save",invalid);}}if(best!=null)return best;if(rejected!=null)throw new SaveException("no valid save; newest and fallback records are invalid",rejected);throw new SaveException("save slot is empty");}catch(SaveException e){throw e;}catch(Exception e){throw new SaveException("RecordStore read failed",e);}}
 public void close(){try{records.close();}catch(Exception ignored){}}
 private int readInt(byte[] b,int p)throws SaveException{if(b==null||p<0||p+4>b.length)throw new SaveException("truncated transaction record");return((b[p]&255)<<24)|((b[p+1]&255)<<16)|((b[p+2]&255)<<8)|(b[p+3]&255);}
}
